[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
monitor_rts = 0
monitor_dtr = 0

lib_deps =
    NewPing
    PID
    AsyncTCP

; Build options
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DARDUINO_LOOP_STACK_SIZE=8192

; Upload options
upload_speed = 921600